export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
export const GET_CURRENT_USER_COMPANY_SUCCESS = 'GET_CURRENT_USER_COMPANY_SUCCESS';
export const GET_CURRENT_USER_COMPANY_FAILURE = 'GET_CURRENT_USER_COMPANY_FAILURE';


//feature actions
export const GET_ALL_FEATURE = "GET_ALL_FEATURE";
export const GET_ALL_FEATURE_SUCCESS = "GET_ALL_FEATURE_SUCCESS";
export const GET_ALL_FEATURE_FAILURE = "GET_ALL_FEATURE_FAILURE";

export const GET_ALL_GROUP_NAME = "GET_ALL_GROUP_NAME";
export const GET_ALL_GROUP_NAME_SUCCESS = "GET_ALL_GROUP_NAME_SUCCESS";
export const GET_ALL_GROUP_NAME_FAILURE = "GET_ALL_GROUP_NAME_FAILURE";

export const ADD_FEATURE = "ADD_FEATURE";
export const ADD_FEATURE_SUCCESS = "ADD_FEATURE_SUCCESS";
export const ADD_FEATURE_FAILURE = "ADD_FEATURE_FAILURE";

//customers actions
export const GET_ALL_CUSTOMERS="GET_ALL_CUSTOMERS";
export const GET_ALL_CUSTOMERS_SUCCESS="GET_ALLCUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAILURE="GET_ALLCUSTOMERS_FAILURE";
export const ADD_CUSTOMER="ADD_CUSTOMER";
export const ADD_CUSTOMER_SUCCESS="ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE="ADD_CUSTOMER_FAILURE";
export const DELETE_CUSTOMER="DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS="DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE="DELETE_CUSTOMER_FAILURE";
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS="UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE="UPDATE_CUSTOMER_FAILURE";


//Category actions
export const CLIENT_GET_ALL_CATEGORY_SUCCESS="CLIENT_GET_ALL_CATEGORY_SUCCESS";
export const CLIENT_GET_ALL_CATEGORY_FAILURE="CLIENT_GET_ALL_CATEGORY_FAILURE";
export const CLIENT_GET_ALL_CATEGORY="CLIENT_GET_ALL_CATEGORY";


export const CATEGORY_UPLOAD_PICTURE_SUCCESS="CATEGORY_UPLOAD_PICTURE_SUCCESS";
export const CATEGORY_UPLOAD_PICTURE_FAILURE="CATEGORY_UPLOAD_PICTURE_FAILURE";
export const CATEGORY_UPLOAD_PICTURE="CATEGORY_UPLOAD_PICTURE";

export const  CATEGORY_UPLOAD_PICTURE_TOKEN_FAILURE="CATEGORY_UPLOAD_PICTURE_TOKEN_FAILURE";
export const  CATEGORY_UPLOAD_PICTURE_TOKEN_SUCCESS="CATEGORY_UPLOAD_PICTURE_TOKEN_SUCCESS";

export const  GET_ALL_PICTURES_SUCCESS="GET_ALL_PICTURES_SUCCESS";
export const  GET_ALL_PICTURES_FAILURE="GET_ALL_PICTURES_FAILURE";

