export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";
export const GET_CURRENT_USER_COMPANY_SUCCESS =
  "GET_CURRENT_USER_COMPANY_SUCCESS";
export const GET_CURRENT_USER_COMPANY_FAILURE =
  "GET_CURRENT_USER_COMPANY_FAILURE";

//feature actions
export const GET_ALL_FEATURE = "GET_ALL_FEATURE";
export const GET_ALL_FEATURE_SUCCESS = "GET_ALL_FEATURE_SUCCESS";
export const GET_ALL_FEATURE_FAILURE = "GET_ALL_FEATURE_FAILURE";

export const GET_ALL_GROUP_NAME = "GET_ALL_GROUP_NAME";
export const GET_ALL_GROUP_NAME_SUCCESS = "GET_ALL_GROUP_NAME_SUCCESS";
export const GET_ALL_GROUP_NAME_FAILURE = "GET_ALL_GROUP_NAME_FAILURE";

export const ADD_FEATURE = "ADD_FEATURE";
export const ADD_FEATURE_SUCCESS = "ADD_FEATURE_SUCCESS";
export const ADD_FEATURE_FAILURE = "ADD_FEATURE_FAILURE";

//Client product
export const CLIENT_GET_ALL_PRODUCT = "CLIENT_GET_ALL_PRODUCT";
export const CLIENT_GET_ALL_PRODUCT_SUCCESS = "CLIENT_GET_ALL_PRODUCT_SUCCESS";
export const CLIENT_GET_ALL_PRODUCT_FAILURE = "CLIENT_GET_ALL_PRODUCT_FAILURE";

export const CLIENT_GET_DETAIL_PRODUCT = "CLIENT_GET_DETAIL_PRODUCT";
export const CLIENT_GET_DETAIL_PRODUCT_SUCCESS =
  "CLIENT_GET_DETAIL_PRODUCT_SUCCESS";
export const CLIENT_GET_DETAIL_PRODUCT_FAILURE =
  "CLIENT_GET_DETAIL_PRODUCT_FAILURE";
